app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("accounts/", include("allauth.urls")),
    path("summernote/", include("django_summernote.urls")),
    # path('', include('social_django.urls', namespace='social')),  # enable for social login
]

if settings.SIMPLE_SENDGRID_ENABLED:
    urlpatterns.append(path("simple-sendgrid/", include("simple_sendgrid.urls")))

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend([path("__debug__/", include(debug_toolbar.urls))])

simple_sendgrid/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import *

app_name = "simple-sendgrid"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("test", TestView.as_view(), name="test"),
]

base/models.py
from django.db import models

# Create your models here.

simple_sendgrid/models.py
from django.db import models

# Create your models here.

simple_sendgrid/forms.py
from django import forms
from django.forms.widgets import TextInput
from django_summernote.widgets import SummernoteWidget

from .mail import send_mail


class TestMailForm(forms.Form):
    subject = forms.CharField()
    from_name = forms.CharField(initial="John Doe")
    from_email = forms.CharField()
    to = forms.EmailField()
    body = forms.CharField(widget=SummernoteWidget())
    reply_to = forms.CharField(required=False)

    def send_mail(self):
        f = self.cleaned_data
        subject = f["subject"]
        from_email = '"{name}" <{email}>'.format(
            name=f["from_name"], email=f["from_email"]
        )
        to = [f["to"]]
        body = f["body"]
        reply_to = f["reply_to"]
        if not reply_to:
            reply_to = None

        send_mail(subject, body, from_email, to, reply_to=reply_to)

base/views.py
from django.shortcuts import render

simple_sendgrid/views.py
import traceback

from django.shortcuts import render
from django.views.generic import TemplateView, View

from .forms import TestMailForm
from .mixins import SuperUserRequiredMixin


class IndexView(SuperUserRequiredMixin, TemplateView):
    template_name = "simple_sendgrid/index.html"


class TestView(SuperUserRequiredMixin, View):
    template_name = "simple_sendgrid/test.html"

    def get(self, request, *args, **kwargs):
        test_mail_form = TestMailForm()
        context = dict(form=test_mail_form)
        return render(self.request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        test_mail_form = TestMailForm(request.POST)
        message = None
        if test_mail_form.is_valid():
            try:
                test_mail_form.send_mail()
            except Exception as e:
                message = traceback.format_exc()
            else:
                message = "Success! The email should have been sent to {}".format(
                    test_mail_form.cleaned_data["to"]
                )
        else:
            message = "Invalid data"

        context = dict(form=test_mail_form, message=message)

        return render(self.request, self.template_name, context=context)

simple_sendgrid/templates/simple_sendgrid/base.html
{% load static %}

<!-- Uses boilerplate from http://html5boilerplate.com -->
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" />

  <link rel="stylesheet" href="{% static 'simple_sendgrid/css/styles.css' %}">

  {% block head %}
  {% endblock head%}

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous">
    </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
</head>

<body>
  <!--[if lt IE 7]>
      <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
  <div class="container pt-5">
    <a href="{% url 'simple-sendgrid:index' %}" class="text-decoration-none">
      <h1>simple-sendgrid</h1>
    </a>
    <p>A simple app for sending dynamic template emails via SendGrid. By Namgyu Ho (its@namgyu.io).</p>
    <hr>
  </div>

  {% block body %}
  {% endblock body %}

  {% block body_script %}
  {% endblock body_script %}
</body>

</html>

simple_sendgrid/templates/simple_sendgrid/index.html
{% extends 'simple_sendgrid/base.html' %}

{% block body %}
<div class="container py-4">
  <h3>Console</h3>
  <div class="row">
    <!-- MANAGEMENT -->
    <div class="col-12 col-md-5">
      <a href="{% url 'simple-sendgrid:test' %}" class="btn btn-light btn-block btn-lg text-left mb-2 px-4">
        Email Test
      </a>
    </div>
  </div>
</div>
{% endblock %}

simple_sendgrid/templates/simple_sendgrid/test.html
{% extends 'simple_sendgrid/base.html' %}
{% load bootstrap4 %}

{% block body %}
<div class="container py-4">
  <div class="row">
    <div class="col-12 col-md-4 mb-4">
      <h2>Mail Test</h3>
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          <button class="btn btn-primary" type="submit">Send Mail</button>
        </form>
    </div>
    {% if message %}
    <div class="col-12 col-md-8 mb-4">
      <h2>Results</h2>
      <div style="font-family: monospace;">
        {{ message|escape|linebreaksbr }}
      </div>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}