app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("accounts/", include("allauth.urls")),
    path("summernote/", include("django_summernote.urls")),
    # path('', include('social_django.urls', namespace='social')),  # enable for social login
]

if settings.SIMPLE_SENDGRID_ENABLED:
    urlpatterns.append(path("simple-sendgrid/", include("simple_sendgrid.urls")))

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend([path("__debug__/", include(debug_toolbar.urls))])

core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import *

app_name = "core"

urlpatterns = [
    path("", LandingView.as_view(), name="landing"),
    path("photos/", PhotoListView.as_view(), name="photo-list"),
    path("photos/<slug:slug>/", PhotoDetailView.as_view(), name="photo-detail"),
    path("index", IndexView.as_view(), name="index"),
]

simple_sendgrid/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import *

app_name = "simple-sendgrid"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("test", TestView.as_view(), name="test"),
]

base/models.py
from django.db import models

# Create your models here.

core/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.templatetags.static import static

User = get_user_model()


class Photo(models.Model):
    votes = models.IntegerField(default=0)
    average = models.FloatField(default=0)
    total = models.FloatField(default=0)

    def update(self):
        selections = self.vote_set.values("selection").annotate(models.Count("user")).all()
        votes = 0
        total = 0
        for s in selections:
            votes += s["user__count"]
            total += Vote.selection_to_integer(s["selection"]) * s["user__count"]
        self.votes = votes
        self.total = total
        self.average = total /votes
        self.save()

    @property
    def src(self):
        if self.id > 982:
            return ""
        else:
            return static("core/media/grad/grad{:03d}.jpg".format(self.id))

    @property
    def thumb_src(self):
        if self.id > 982:
            return ""
        else:
            return static("core/media/grad_thumb/grad{:03d}.jpg".format(self.id))

    @property
    def name(self):
        return "서강대단체{}.jpg".format(self.id)


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    photo = models.ForeignKey(Photo, on_delete=models.CASCADE)

    GOOD = 'GD'
    OKAY = 'OK'
    BAD = 'BD'
    selection_choices = [
        (GOOD, 'Great (5)'),
        (OKAY, 'Okay (3)'),
        (BAD, 'Bad (1)'),
    ]
    selection = models.CharField(max_length=2, choices=selection_choices)

    @classmethod
    def selection_to_integer(cls, selection):
        if selection == cls.GOOD:
            return 5
        elif selection == cls.OKAY:
            return 3
        elif selection == cls.BAD:
            return 1
        else:
            raise AssertionError()

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["user", "photo"], name="user_photo_unique")
        ]

core/account/forms.py
import hashlib

from django import forms
from django.utils.translation import gettext_lazy as _
import allauth


class SignupForm(allauth.account.forms.SignupForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["first_name"] = forms.fields.CharField(
            label=_("First name"), max_length=30
        )
        self.fields["last_name"] = forms.fields.CharField(
            label=_("Last name"), max_length=150
        )
        self.fields["secret"] = forms.fields.CharField(
            label=_("Secret Key"), max_length=150
        )

    def clean_secret(self):
        data = self.cleaned_data['secret']
        hashed = hashlib.sha256(str.encode(data)).hexdigest()
        answer = '6e73edb1ca687aba0fc1247c2215b3f6106ca16835677d63cd29a2049c8fc7be'
        if hashed != answer:
            raise forms.ValidationError("Incorrect secret key!")
        return data

    def save(self, request):
        user = super().save(request)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.save()
        return user

core/forms.py
from django import forms

from core.models import *


class VoteForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["user"].disabled = True
        self.fields["photo"].disabled = True

    class Meta:
        model = Vote
        fields = ["user", "photo", "selection"]
        widgets = {
            "user": forms.HiddenInput(),
            "photo": forms.HiddenInput(),
        }

base/views.py
from django.shortcuts import render

core/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count, Q, OuterRef, Subquery
from django.urls import reverse
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView
from django.views.generic.detail import SingleObjectMixin

from core.forms import VoteForm
from core.models import Photo, Vote


class LandingView(TemplateView):
    template_name = "core/landing.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class IndexView(TemplateView):
    template_name = "core/index.html"


class PhotoListView(LoginRequiredMixin, TemplateView):
    template_name = "core/photo_list.html"

    def get_photo_list(self):
        photos = Photo.objects.all().annotate(bad=Count("vote", filter=Q(vote__selection=Vote.BAD)),
                                              okay=Count("vote", filter=Q(vote__selection=Vote.OKAY)),
                                              good=Count("vote", filter=Q(vote__selection=Vote.GOOD)))
        if self.request.GET.get("sort") == "rank":
            photos = photos.order_by("-average")
        votes = Vote.objects.filter(user=self.request.user).all()
        votes_by_photo = {vote.photo_id: vote for vote in votes}
        for photo in photos:
            photo.vote = votes_by_photo.get(photo.id)
        return photos

    def get_context_data(self, **kwargs):
        User = get_user_model()
        context = super().get_context_data(**kwargs)
        max_votes = Photo.objects.count() * User.objects.count()
        context["photo_list"] = self.get_photo_list()
        context["total_votes"] = Vote.objects.count()
        context["max_votes"] = max_votes
        context["progress"] = Vote.objects.count() / max_votes * 100
        context["users"] = User.objects.annotate(Count("vote")).order_by("-vote__count")
        context["sort_by_rank"] = self.request.GET.get("sort") == "rank"
        return context


class PhotoDetailView(LoginRequiredMixin, SingleObjectMixin, FormView):
    """
    self.object = Photo {
        next: next photo
        previous: previous photo
        vote: current user's vote on photo
    }
    """
    template_name = "core/photo_detail.html"
    model = Photo
    slug_url_kwarg = "slug"
    slug_field = "id"
    context_object_name = "photo"
    form_class = VoteForm

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return self.render_to_response(self.get_context_data())

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_object(self, queryset=None):
        object = super().get_object(queryset)
        object.vote = object.vote_set.filter(user=self.request.user).first()
        return object

    def get_queryset(self):
        next_photo = Photo.objects.filter(id__gt=OuterRef("id")).order_by("id").values("id")[:1]
        previous_photo = Photo.objects.filter(id__lt=OuterRef("id")).order_by("-id").values("id")[:1]
        return Photo.objects.all().annotate().annotate(next=Subquery(next_photo)).annotate(
            previous=Subquery(previous_photo))

    def get_initial(self):
        initial = super().get_initial()
        initial["photo"] = self.object.id
        initial["user"] = self.request.user.id
        return initial

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if self.object.vote:
            kwargs.update({'instance': self.object.vote})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["next_id"] = self.object.next
        context["previous_id"] = self.object.previous
        return context

    def form_valid(self, form):
        form.save()
        self.object.update()
        return super().form_valid(form)

    def get_success_url(self):
        if self.object.next:
            return reverse("core:photo-detail", args=[self.object.next])
        else:
            return reverse("core:photo-list")

core/templates/core/base.html
{% load static %}

{# Boilerplate from http://html5boilerplate.com #}
<!DOCTYPE html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
	<!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-165441261-3"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-165441261-3');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;700;800&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'core/css/base.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">


  <title>Fooddeuk</title>

  <meta property="og:url" content="">
  <meta property="og:title" content="Fooddeuk">
  <meta property="og:type" content="website">
  <meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'core/img/og_image.jpg' %}">
  <meta property="og:description" content="Fooddeuk is love. Fooddeuk is life.">

  <link rel="shortcut icon" type="image/png" href="{% static 'core/img/favicon.png' %}"/>

  {% block head %}
  {% endblock head %}

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
          integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
          integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
          integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>
</head>

<body>
<!--[if lt IE 7]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a>
  to improve your experience.</p>
<![endif]-->

{% block body %}
{% endblock body %}

{% include 'base/extra_body.html' %}

{% block body_script %}
{% endblock body_script %}
</body>

</html>

core/templates/core/footer.html
<div class="footer">
  <div class="container">
    <div class="py-5">
      <span class="footer-title">Food Selector</span>
    </div>
    <div class="py-2">
      <span class="footer-copyright">Food Selector © {% now "Y" %} FOODDEUK, All Rights Reserved.</span>
    </div>
  </div>
</div>

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/navbar.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/header.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/footer.css' %}">
{% endblock head %}

{% block body %}

  {% include 'core/navbar.html' %}

  <div class="content">
    <div class="container py-5">
      <h2>This is a placeholder app for django-template</h2>
      <p><i class="fas fa-rocket"></i> Good luck on your project!</p>

      <img class="hero-gif" src="{% static 'core/media/grad.gif' %}">

      {% bootstrap_messages as messages %}
      {% if messages.strip %} {# #}
        <h4 class="mt-4">Here are some Bootstrap messages</h4>
        <p>{{ messages }}</p>
      {% endif %}

    </div>
  </div>

  {% include 'core/footer.html' %}

{% endblock body %}
{% block body_script %}
{% endblock body_script %}

core/templates/core/landing.html
{% extends 'core/base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/navbar.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/header.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/footer.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/landing.css' %}">
{% endblock head %}

{% block body %}
  <div class="landing-container">
    <img class="landing-gif animate__animated animate__fadeIn animate__slower animate__delay-1s"
         src="{% static 'core/media/grad.gif' %}">
    <div class="landing-content animate__animated animate__fadeIn animate__slower animate__delay-2s">
      <div class="container">
        <div class="title">Fooddeuk</div>
        <div class="subtitle mb-1">Fooddeuk is love. Fooddeuk is life.</div>
        <div class="subtitle mb-3">Even after graduation.</div>
        <a href="{% url 'core:photo-list' %}" class="btn btn-landing">
          Vote Now<i class="fas fa-chevron-right ml-2"></i>
        </a>
        <a href="https://github.com/itsnamgyu/fooddeuk" class="btn btn-landing">
          <i class="fas fa-star mr-2"></i>Star on Github
        </a>
      </div>
    </div>
    <div class="landing-copyright">
      © {% now "Y" %} Fooddeuk. All rights reserved.
    </div>
  </div>

{% endblock body %}
{% block body_script %}
{% endblock body_script %}

core/templates/core/navbar.html
{% load static %}

<nav class="fixed-top">
  <div class="navbar-top">
    <div class="container">
      <div class="d-flex justify-content-end">
        {% if request.user.is_authenticated %}
          <a class="btn navbar-top-button" href="{% url 'account_logout' %}">SIGN OUT</a>
        {% else %}
          <a class="btn navbar-top-button" href="{% url 'account_login' %}">LOG IN</a>
          <a class="btn navbar-top-button" href="{% url 'account_signup' %}">SIGN UP</a>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="navbar-middle navbar navbar-expand-lg">
    <div class="container">
      <a class="navbar-brand nav-title" href="{% url 'core:index' %}">
       Food Selector
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
              aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          {% for menu in '' %}
            {% if not menu.disabled %}
              <li class="nav-item">
                <a class="nav-link {% if menu.active %}active{% endif %}" href="{{ menu.href }}">{{ menu.title }}</a>
              </li>
            {% endif %}
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</nav>

core/templates/core/photo_detail.html
{% extends 'core/base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/navbar.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/header.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/footer.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/photo.css' %}">
{% endblock head %}

{% block body %}
  <div class="background">
    <div class="container py-4">
      <a href="{% url 'core:photo-list' %}" class="btn btn-back pl-0 text-white"><i
          class="fas fa-chevron-left mr-2"></i>Back</a>
      <div class="title">Photo {{ photo.id }}</div>
      <div class="name mb-4">{{ photo.name }}</div>
      <div class="photo-wrapper">
        {% if previous_id %}
          <a href="{% url 'core:photo-detail' previous_id %}" class="photo-left"></a>
        {% endif %}
        {% if next_id %}
          <a href="{% url 'core:photo-detail' next_id %}" class="photo-right"></a>
        {% endif %}
        <img class="photo mb-4" src="{{ photo.src }}">
      </div>
      <div class="text-center">
        <form method="post" class="d-inline-block">
          {% csrf_token %}
          <input name="selection" value="BD" hidden>
          <button class="btn btn-outline-white {% if form.selection.initial == 'BD' %}active {% endif %}">Bad (1)</button>
        </form>
        <form method="post" class="d-inline-block mx-1 mx-md-4">
          {% csrf_token %}
          <input name="selection" value="OK" hidden>
          <button class="btn btn-outline-white {% if form.selection.initial == 'OK' %}active {% endif %}">Okay (3)</button>
        </form>
        <form method="post" class="d-inline-block">
          {% csrf_token %}
          <input name="selection" value="GD" hidden>
          <button class="btn btn-outline-white {% if form.selection.initial == 'GD' %}active {% endif %}">Good (5)</button>
        </form>
      </div>
    </div>
  </div>
{% endblock body %}
{% block body_script %}
{% endblock body_script %}

core/templates/core/photo_list.html
{% extends 'core/base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/navbar.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/header.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/footer.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/photo_list.css' %}">
{% endblock head %}

{% block body %}
  <div class="background">
    <div class="container py-5">
      <a href="{% url 'core:landing' %}" class="btn btn-back pl-0">
        <i class="fas fa-chevron-left mr-2"></i>Back</a>
      <div class="mb-4">
        <div class="photo-list-title mb-2">VoteForFooddeuk</div>
        <div class="photo-list-stat mb-1"><i class="fas fa-vote-yea mr-2"></i>Votes: {{ total_votes }}/{{ max_votes }}</div>
        <div class="photo-list-stat mb-1"><i class="fas fa-spinner mr-2"></i>Progress: {{ progress|floatformat:2 }}%
        </div>
      </div>
      <div class="mb-4">
        <div class="photo-list-header mb-2">Individual Progress</div>
        <div class="row">
          {% for user in users %}
            {% if user.last_name %}
              <div class="col-6 col-md-4 col-xl-3">
                <div class="photo-list-user mb-2"><i
                    class="fas fa-vote-yea mr-2"></i>{{ user.last_name }}{{ user.first_name }}: {{ user.vote__count }}
                </div>
              </div>
            {% endif %}
          {% endfor %}
        </div>
      </div>
      <div class="d-flex mb-2 align-items-center">
        <div class="photo-list-header mb-2">All Photos</div>
        <div class="btn-group ml-auto">
          <a href="{% url 'core:photo-list' %}" class="btn btn-light {% if not sort_by_rank %}active{% endif %}">Index</a>
          <a href="{% url 'core:photo-list' %}?sort=rank" class="btn btn-light {% if sort_by_rank %}active{% endif %}">Rank</a>
        </div>
      </div>
      <div class="row">
        {% for photo in photo_list %}
          <div class="col-6 col-md-4 col-xl-3 mb-5">
            <a href="{% url 'core:photo-detail' photo.id %}">
              <div class="photo-listing">
                <img class="preview" src="{{ photo.thumb_src }}">
                <div class="content">
                  <div class="d-flex">
                    <div class="title">
                      {% if photo.vote %}
                        <i class="fas fa-check text-success mr-2"></i>
                      {% else %}
                        <i class="fas fa-ellipsis-h mr-2"></i>
                      {% endif %}
                      Photo {{ photo.id }}
                    </div>
                    <div class="ml-auto rank">#{{ forloop.counter }}</div>
                  </div>
                  <hr>
                  <div class="stat"><i class="fas fa-star mr-2"></i>{{ photo.average|floatformat:2 }} Points</div>
                  <div class="stat"><i class="fas fa-vote-yea mr-2"></i>{{ photo.votes }} Votes
                    ({{ photo.bad }}/{{ photo.okay }}/{{ photo.good }})
                  </div>
                </div>
              </div>
            </a>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock body %}
{% block body_script %}
{% endblock body_script %}